from app.models.enums import WordCategory

CORE_WORDS: tuple[tuple[str, WordCategory, str], ...] = (
    ("facture", WordCategory.MONEY, "Voici votre facture du mois."),
    ("montant", WordCategory.MONEY, "Le montant à payer est indiqué en bas."),
    ("payer", WordCategory.MONEY, "Vous devez payer avant la date limite."),
    ("échéance", WordCategory.MONEY, "L'échéance est fixée au 30 du mois."),
    ("retard", WordCategory.MONEY, "Des frais de retard seront ajoutés."),
    ("reçu", WordCategory.MONEY, "Gardez ce reçu comme preuve de paiement."),
    ("compte", WordCategory.MONEY, "Le montant sera prélevé sur votre compte."),
    ("ordonnance", WordCategory.HEALTH, "Présentez l'ordonnance à la pharmacie."),
    ("médicament", WordCategory.HEALTH, "Prenez ce médicament après le repas."),
    ("comprimé", WordCategory.HEALTH, "Prendre un comprimé le matin."),
    ("matin", WordCategory.HEALTH, "Un comprimé le matin et un le soir."),
    ("soir", WordCategory.HEALTH, "Prendre le sirop le soir."),
    ("jours", WordCategory.HEALTH, "Le traitement dure sept jours."),
    ("rendez-vous", WordCategory.HEALTH, "Votre rendez-vous est lundi à 10 heures."),
    ("analyse", WordCategory.HEALTH, "Faites cette analyse à jeun."),
    ("école", WordCategory.SCHOOL, "L'école reprend le lundi."),
    ("inscription", WordCategory.SCHOOL, "L'inscription se fait au secrétariat."),
    ("bulletin", WordCategory.SCHOOL, "Le bulletin du trimestre est disponible."),
    ("convocation", WordCategory.SCHOOL, "Vous êtes convoqué à une réunion des parents."),
    ("élève", WordCategory.SCHOOL, "L'élève doit apporter ses cahiers."),
    ("date", WordCategory.ADMIN, "Indiquez la date de naissance."),
    ("signature", WordCategory.ADMIN, "Ajoutez votre signature en bas de la page."),
    ("adresse", WordCategory.ADMIN, "Écrivez votre adresse complète."),
    ("demande", WordCategory.ADMIN, "Votre demande a bien été reçue."),
    ("attestation", WordCategory.ADMIN, "Joignez une attestation de domicile."),
    ("pièce", WordCategory.ADMIN, "Apportez une pièce d'identité."),
    ("dossier", WordCategory.ADMIN, "Votre dossier est complet."),
    ("nom", WordCategory.COMMON, "Écrivez votre nom en majuscules."),
    ("prénom", WordCategory.COMMON, "Le prénom est obligatoire."),
    ("téléphone", WordCategory.COMMON, "Laissez votre numéro de téléphone."),
    ("avant", WordCategory.COMMON, "Répondez avant vendredi."),
    ("obligatoire", WordCategory.COMMON, "Ce champ est obligatoire."),
)
